export const KIOSK_HEADER_FULL_HEIGHT = 148;
export const KIOSK_HEADER_COLLAPSED_HEIGHT = 92;
export const KIOSK_HEADER_SHRINK_THRESHOLD = 96;
export const KIOSK_CATEGORY_BAR_HEIGHT = 64;
export const KIOSK_SCROLL_PADDING = KIOSK_HEADER_COLLAPSED_HEIGHT + KIOSK_CATEGORY_BAR_HEIGHT + 12;
