export const KIOSK_HEADER_BASE_HEIGHT = 104;
export const KIOSK_CATEGORY_BAR_HEIGHT = 64;
export const KIOSK_CHROME_OFFSET = KIOSK_HEADER_BASE_HEIGHT + KIOSK_CATEGORY_BAR_HEIGHT;
export const KIOSK_HEADER_SHRINK_THRESHOLD = 120;
