name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo files
        run: |
          ls -la
          echo "----- package.json -----"
          cat package.json
